root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
bin = "tmp/main"
cmd = "go build -o ./tmp/main ."
delay = 1000
exclude_dir = ["assets", "tmp", "vendor", "testdata"]
exclude_regex = ["_test.go"]
include_ext = ["go", "tpl", "tmpl", "html"]
log = "build-errors.log"
# Remove boolean flags to avoid Air env conversion issues

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = true

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true