INSERT INTO categories (name) VALUES
    ('🥬Produce'),
    ('🥛Dairy & Eggs'),
    ('🥩Meat & Seafood'),
    ('🥖Bakery'),
    ('🍝Pasta & Grains'),
    ('🥤Beverages'),
    ('🍬Pantry Staples'),
    ('💧Refrigerated'),
    ('❄️Frozen'),
    ('🏠Household Supplies'),
    ('🪥Personal Care');

INSERT INTO stores (name) VALUES
    ('Walmart'),
    ('Costco'),
    ('BJ''s'),
    ('Trader Joe''s'),
    ('Aldi'),
    ('Giant'),
    ('Target');

INSERT INTO ingredients (name, category_id, store_id) VALUES
    ('Bananas', 1, 1),
    ('Romaine Lettuce', 1, 2),
    ('Avocados', 1, 4),
    ('Strawberries', 1, 5),
    ('Whole Milk', 2, 1),
    ('Cheddar Cheese', 2, 2),
    ('Greek Yogurt', 2, 4),
    ('Dozen Eggs', 2, 5),
    ('Chicken Breast', 3, 1),
    ('Ground Beef', 3, 2),
    ('Salmon Fillet', 3, 3),
    ('Bacon', 3, 6),
    ('White Bread', 4, 1),
    ('Bagels', 4, 2),
    ('Croissants', 4, 4),
    ('Brioche Buns', 4, 7),
    ('Spaghetti', 5, 1),
    ('Brown Rice', 5, 2),
    ('Quinoa', 5, 4),
    ('Macaroni', 5, 6),
    ('Orange Juice', 6, 1),
    ('Coffee Beans', 6, 4),
    ('Green Tea', 6, 7),
    ('Sparkling Water', 6, 2),
    ('Peanut Butter', 7, 1),
    ('Olive Oil', 7, 2),
    ('All-Purpose Flour', 7, 6),
    ('Granulated Sugar', 7, 5),
    ('Hummus', 8, 4),
    ('Butter', 8, 2),
    ('Tofu', 8, 4),
    ('Cottage Cheese', 8, 6),
    ('Frozen Pizza', 9, 1),
    ('Ice Cream', 9, 2),
    ('Frozen Vegetables', 9, 5),
    ('Waffles', 9, 7),
    ('Paper Towels', 10, 1),
    ('Laundry Detergent', 10, 2),
    ('Dish Soap', 10, 7),
    ('Trash Bags', 10, 6),
    ('Toothpaste', 11, 1),
    ('Shampoo', 11, 2),
    ('Body Wash', 11, 6),
    ('Deodorant', 11, 7);